### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by cryptix** [ssbc/scuttlebutt-protocol-guide#11]
I just realized that the links to the go implementation still point to my username, before we moved to the cryptoscope org.

I wrote this 3 liner to get a list of links and their status - might be cool to have it as a commit hook or something but since there were no build targets or makefiles I didn't make a PR yet:

```bash
cat index.html | pup 'a attr{href}' | grep https | while read url
do
    code=$(curl -s -o /dev/null -I -w "%{http_code}" $url)
    echo $url: $code
done
```

(the pup tool to use css selectors in HTML can be found [here](https://github.com/ericchiang/pup))

Here is the output it gave me:

- [x] https://github.com/ssbc/scuttlebutt-protocol-guide: 200
- [x] https://www.scuttlebutt.nz/: 200
- [x] https://github.com/dominictarr/broadcast-stream/blob/master/index.js: 200
- [x] https://github.com/ssbc/scuttlebot/blob/master/plugins/local.js: 200
- [x] https://github.com/auditdrivencrypto/secret-handshake/blob/master/protocol.js: 200
- [x] https://github.com/auditdrivencrypto/secret-handshake/blob/master/crypto.js: 200
- [x] https://github.com/pferreir/PySecretHandshake/blob/master/secret_handshake/crypto.py: 200
- [x] https://github.com/cryptix/secretstream/blob/master/secrethandshake/state.go: 301
- [x] https://github.com/cryptix/secretstream/blob/master/secrethandshake/conn.go: 301
- [x] https://github.com/AljoschaMeyer/shs1-c/blob/master/src/shs1.c: 200
- [x] https://git.scuttlebot.io/%25133ulDgs%2FoC1DXjoK04vDFy6DgVBB%2FZok15YJmuhD5Q%3D.sha256/blob/fd953a1e72b4b16e6e5a74bcf2f893dbf1407ce4/sbotc.c: 200
- [x] https://dominictarr.github.io/secret-handshake-paper/shs.pdf: 200
- [x] https://github.com/dominictarr/pull-box-stream/blob/master/index.js: 200
- [x] https://github.com/pferreir/PySecretHandshake/blob/master/secret_handshake/boxstream.py: 200
- [x] https://github.com/cryptix/secretstream/blob/master/boxstream/box.go: 301
- [x] https://github.com/cryptix/secretstream/blob/master/boxstream/unbox.go: 301
- [x] https://github.com/AljoschaMeyer/box-stream-c/blob/master/src/box-stream.c: 200
- [x] https://git.scuttlebot.io/%25133ulDgs%2FoC1DXjoK04vDFy6DgVBB%2FZok15YJmuhD5Q%3D.sha256/blob/fd953a1e72b4b16e6e5a74bcf2f893dbf1407ce4/sbotc.c: 200
- [x] https://github.com/dominictarr/packet-stream-codec/blob/master/index.js: 200
- [x] https://github.com/pferreir/pyssb/blob/master/ssb/packet_stream.py: 200
- [x] https://github.com/pferreir/pyssb/blob/master/ssb/muxrpc.py: 200
- [x] https://github.com/cryptix/go-muxrpc/blob/master/client.go: 301
- [x] https://git.scuttlebot.io/%25133ulDgs%2FoC1DXjoK04vDFy6DgVBB%2FZok15YJmuhD5Q%3D.sha256/blob/fd953a1e72b4b16e6e5a74bcf2f893dbf1407ce4/sbotc.c: 200
- [x] https://github.com/ssbc/ssb-keys/blob/master/index.js: 200
- [x] https://github.com/ssbc/ssb-feed/blob/master/validator.js: 200
- [x] https://github.com/pferreir/pyssb/blob/master/ssb/feed/models.py: 200
- [x] https://www.ecma-international.org/ecma-262/6.0/#sec-json.stringify: 200
- [x] https://www.ecma-international.org/ecma-262/6.0/#sec-quotejsonstring: 200
- [x] https://www.ecma-international.org/ecma-262/6.0/#sec-tostring-applied-to-the-number-type: 200
- [x] https://github.com/ssbc/secure-scuttlebutt/blob/master/indexes/clock.js: 301
- [x] https://github.com/ssbc/multiblob/blob/master/index.js: 200
- [x] https://github.com/ssbc/ssb-blobs/blob/master/inject.js: 200
- [x] https://github.com/ssbc/ssb-friends/blob/master/alg.js: 404
- [x] https://github.com/ssbc/scuttlebot/blob/master/plugins/invite.js: 200
- [x] https://github.com/ssbc/ssb-keys/blob/master/index.js: 200
- [x] https://github.com/auditdrivencrypto/private-box/blob/master/index.js: 200

**Comment by vtduncan** [comment]
Thanks for finding these! I think I fixed all the remaining ones and I added a script to find broken links in the future.

ps. I ticked all the boxes in your comment :)
