### ISSUE TITLE
Feed signature JSON stringify 

### ISSUE THREAD

**Issue by atoulme** [ssbc/scuttlebutt-protocol-guide#14]
When creating the signature of a feed message, the guide mentions to apply JSON.stringify with a series of guidelines on how to pretty print JSON.

Those guidelines do not indicate which line ending characters to use: `\n` or`\r\n`?

**Comment by AljoschaMeyer** [comment]
It's `\n`. For a precise definition, see https://spec.scuttlebutt.nz/datamodel.html#signing-encoding-arrays

**Comment by atoulme** [comment]
I'll submit a patch.

**Comment by vtduncan** [comment]
This is fixed in 7b43496.
