### ISSUE TITLE
Maximum message size

### ISSUE THREAD

**Issue by AljoschaMeyer** [ssbc/scuttlebutt-protocol-guide#21]
Mention the maximum message size (which effectively restricts the set of valid `content` objects. [Spec entry](https://spec.scuttlebutt.nz/datamodel.html#legacy-length-computation):

> Ssb places a limit on the size of legacy messages. To compute the length of a legacy value, compute the signing encoding (which is always valid unicode), reencode that unicode as utf16, then count the number of code units.

A message can consist of at most 16385 utf-16 code units.

**Comment by vtduncan** [comment]
Thank you @AljoschaMeyer for doing this really difficult work of documenting all these quirks in the protocol. I really appreciate that you have combed through this guide and found these errors where it doesn't line up with the spec.

It's going to be a while before I can dedicate the time to understanding these details, but I just wanted to say thanks for figuring this out.

**Comment by AljoschaMeyer** [comment]
To be fair, I only revisited the [feeds](https://ssbc.github.io/scuttlebutt-protocol-guide/#feeds) section, not the full guide.
