### ISSUE TITLE
Follow publicity

### ISSUE THREAD

**Issue by DavidBruant** [ssbc/scuttlebutt-protocol-guide#37]
I want to send a question on the ssbc protocol, but it's not clear to me where to do that, so i'm trying this repo
I'm happy to move the conversation elsewhere if this is not the right place

From https://ssbc.github.io/scuttlebutt-protocol-guide/ at this time:

> Feeds can follow other feeds. Following is a way of saying “I am interested in the messages posted by this feed”.

> When a user wants to follow another feed their client will post a message to their own feed that looks like:
> (json)
> Later, if the user decides to unfollow this feed, their client can post another message with following set to false.

> A Scuttlebutt feed is a list of all the messages posted by a particular identity. When a user writes a message in a Scuttlebutt client and posts it, that message is put onto the end of their feed.

> The messages in a feed form an append-only log, meaning that once a message is posted it cannot be modified

> One implementation, Patchwork, shows messages up to 2 hops out by default. Messages from feeds 3 hops out are replicated to help keep them available for others

From all of these quotes combined, my understanding of the protocol as it currently is is that who you follow is part of your feed and it is part of it pretty much forever. This means that someone following you knows everyone else you follow

I see a potential privacy concern here. In some cases, the social graph of a person can be considered a private information that indirectly reveals interests or relationships

It's happened [on Facebook](http://w3.salemstate.edu/~pglasser/When_the_Most_Personal_Secrets_Get_Outed_on_Facebook_-_WSJ.pdf) where the platform outed a person to their parent by disclosing a group membership
In this case, the social graph of a person was a privacy-sensitive information she had been careful to not reveal her parents (in this example, it's a group, but it might as well have been the leader of this group or several queer people)

There is also the "finsta" phenomenon where some people create a secundary more private instagram account for many purposes, but a common one being to be more discreet in who they (actually) follow

My question is: does the ssbc team acknowledges keeping the social graph of a person private information as a problem in ssbc scope?
If so, what are the current and future solutions?

All this relies on my current understanding of the ssbc protocol and i apologize for the noise if i misunderstood something in the protocol

**Comment by DavidBruant** [comment]
I think it's still relevant
Having someone from the team read this issue is probably the one thing blocking

Perhaps my lack of understanding of where this discussion should happen (if at all) is what's blocking progress

**Comment by nevercast** [comment]
Stale bot. Please stop.

**Comment by arj03** [comment]
To answer this question, contact messages (following, blocking etc.) can be done privately so you don't leak this information to others. But the information does have social value for you friends. Private groups which will be coming soon will make this even more interesting in that you can disclose this information only to a certain group :)

**Comment by arj03** [comment]
Happe to merge a PR that makes this more clear in the documentation

**Comment by DavidBruant** [comment]
Hi arj03,

I am grateful for your answer!

> To answer this question, contact messages (following, blocking etc.) can be done privately so you don't leak this information to others.

oh ok\
I hadn't seen this option in the protocol or reflected in the Patchwork UI so i was imagining this wasn't an option. 

For clarification purposes, is it an option that exists at the protocol level or is it a client-level implementation where the client keeps a memory of the list of who's being followed independent of the published log?

> But the information does have social value for your friends.

Definitely, it think both sides co-exist; i don't see it as an either/or

The information of who Alice follows can be useful to Bob and Alice is fine with it\
and the same Alice also may be fine with being "followed by" Carol in the sense of her public messages being read by her, but may not be fine with Carol knowing who she follows

> Private groups which will be coming soon will make this even more interesting in that you can disclose this information only to a certain group :)

oh, that's really cool! I'm looking forward to this feature ^^

> Happe to merge a PR that makes this more clear in the documentation

Ok\
Currently, i don't feel i know the protocol and the documentation enough to contribute, but as soon as i do, i'll try to make a PR

**Comment by arj03** [comment]
In SSB any message can be private actually. The way it works is that when you receive a message (or write one) you try to decrypt it, if you can you index it in its decrypted form. For this reason, it is actually just a matter of writing the UI to encrypt these kind of messages. Privately here just means for yourself, but also works with multiple recipients.
