### ISSUE TITLE
protocol svg rendering off on macOS

### ISSUE THREAD

**Issue by jedahan** [ssbc/scuttlebutt-protocol-guide#7]
https://ssbc.github.io/scuttlebutt-protocol-guide/img/format_udp_broadcast.svg

When I open in inkscape, looks fine

but in firefox, chromium, and safari, all the bracked on the bottom are shifted over

<img width="1116" alt="screen shot 2018-07-06 at 12 21 11 pm" src="https://user-images.githubusercontent.com/32407/42389554-1ee0ec6e-8117-11e8-8d96-34c17fed4053.png">

**Comment by vtduncan** [comment]
Fixed in b1c87a3.
